export const CMD_INIT = "init"
export const CMD_CAN_PLACE = "can_place_ship"
export const CMD_PLACE_SHIP = "place_ship"
export const CMD_RANDOM_PLACEMENT = "random_placement"
export const CMD_CLEAR_PLACEMENT = "clear_placement"
export const CMD_START_GAME = "start_game"
export const CMD_ATTACK = "attack"
export const CMD_AI_TURN = "ai_turn"

export const EVT_READY = "ready"
export const EVT_PLACEMENT_STATE = "placement_state"
export const EVT_PLACEMENT_VALID = "placement_valid"
export const EVT_STATE = "state"
export const EVT_ERROR = "error"
